"""
ToolGen Documentation Generator: Generate README from spec and code.

For PoC, we emit basic markdown documentation.
"""
from typing import Dict, Any
import json
import time

# SPDX License header for generated code
LICENSE_HEADER = """# SPDX-License-Identifier: MIT
# Generated by ToolGen (SPICA) — see SBOM.json for details
# This code is synthesized and should be reviewed before production use.

"""

def _format_perf_targets(targets: Dict[str, Any]) -> str:
    """Format performance targets as markdown bullet list."""
    lines = []
    for key, value in targets.items():
        # Convert snake_case to Title Case
        label = key.replace("_", " ").title()
        # Add unit suffixes where appropriate
        if "mb" in key.lower():
            lines.append(f"- **{label}**: {value}MB")
        elif "sec" in key.lower() or "per" in key.lower():
            lines.append(f"- **{label}**: {value}")
        else:
            lines.append(f"- **{label}**: {value}")
    return "\n".join(lines)

def generate_sbom(spec: Dict[str, Any], spec_path: str, impl_style: str = "set") -> Dict[str, Any]:
    """
    Generate Software Bill of Materials for synthesized tool.

    Args:
        spec: Tool specification dict
        spec_path: Path to spec file
        impl_style: Implementation style used

    Returns:
        SBOM dict with metadata
    """
    return {
        "tool_id": spec.get("id", spec.get("tool_id", "unknown")),
        "version": "1.0.0",
        "generator": "ToolGen-SPICA",
        "timestamp": time.time(),
        "generated_from": str(spec_path),
        "impl_style": impl_style,
        "constraints": spec.get("constraints", {}),
        "performance_targets": spec.get("performance_targets", {}),
        "license": "MIT",
        "dependencies": [],  # Currently no external deps
        "safety_checks": {
            "forbidden_apis": spec.get("constraints", {}).get("forbidden_apis", []),
            "sandboxed": True
        }
    }


def add_license_header(code: str) -> str:
    """
    Prepend license header to generated code.

    Args:
        code: Generated Python code

    Returns:
        Code with license header
    """
    return LICENSE_HEADER + code


def generate_docs(spec: Dict[str, Any], code: str) -> str:
    """
    Generate markdown documentation for the tool.
    
    Args:
        spec: Tool specification dict
        code: Generated Python code
    
    Returns:
        Markdown documentation as string
    """
    tool_id = spec["tool_id"]
    description = spec["description"]
    signature = spec["signature"]
    docstring = spec["docstring"]
    
    docs = f'''# {tool_id}

{description}

## Signature

```python
{signature}
```

{docstring}

## Implementation

```python
{code}
```

## Usage Example

```python
from tool import deduplicate_lines

text = """
hello world
hello world
unique line
"""

result = deduplicate_lines(text, threshold=1.0)
print(result)
# Output: hello world\\nunique line
```

## Constraints

- **Forbidden APIs**: {", ".join(spec["constraints"]["forbidden_apis"])}
- **Max Runtime**: {spec["constraints"]["max_runtime_sec"]}s
- **Max Memory**: {spec["constraints"]["max_memory_mb"]}MB

## Performance Targets

{_format_perf_targets(spec["performance_targets"])}

---

Auto-generated by ToolGen
'''
    
    return docs
