"""
SPICA Domain - Generic Test Domain for PHASE Tournaments

Provides generic test execution infrastructure for SPICA instances.
This is the base domain that tournament evaluators use.

Auto-generated by ModuleGenerator from existing spica_* patterns.
"""
import sys
import json
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, asdict

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

logger = logging.getLogger(__name__)


@dataclass
class SPICATestConfig:
    """Configuration for SPICA test execution."""
    max_latency_ms: int = 5000
    max_memory_mb: int = 2048
    max_cpu_percent: float = 80.0
    timeout_seconds: int = 120


@dataclass
class SPICATestResult:
    """Result from a SPICA test run."""
    replica_id: str
    spica_id: str
    status: str  # "pass", "fail", "timeout", "oom"
    exact_match_mean: float = 0.0
    latency_p50_ms: float = 0.0
    latency_p95_ms: float = 0.0
    memory_peak_mb: float = 0.0
    cpu_percent: float = 0.0
    query_count: int = 0
    error_message: Optional[str] = None


class SPICADomain:
    """
    Generic PHASE domain for SPICA instance testing.

    Provides infrastructure for:
    - Running QTIME-accelerated test replicas
    - Aggregating results across replicas
    - Enforcing resource limits and timeouts
    """

    def __init__(self, config: SPICATestConfig):
        """
        Initialize SPICA test domain.

        Args:
            config: SPICATestConfig with test parameters
        """
        self.config = config
        self.results: List[SPICATestResult] = []

    def run_qtime_replicas(
        self,
        instance_paths: List[Path],
        replica_plan: Dict[str, Any]
    ) -> List[SPICATestResult]:
        """
        Run QTIME-accelerated replicas for SPICA instances.

        Args:
            instance_paths: List of SPICA instance directories
            replica_plan: Deterministic replica expansion plan

        Returns:
            List of SPICATestResult objects
        """
        results = []

        for replica in replica_plan["replicas"]:
            replica_id = replica["replica_id"]
            instance_id = replica["instance_id"]

            # Find instance path
            instance_path = None
            for path in instance_paths:
                if instance_id in str(path):
                    instance_path = path
                    break

            if not instance_path:
                logger.warning(f"Instance not found for {instance_id}")
                continue

            # Run test for this replica
            result = self._run_single_replica(
                replica_id=replica_id,
                instance_id=instance_id,
                instance_path=instance_path,
                epoch=replica["epoch"],
                slice_idx=replica["slice"],
                replica_idx=replica["replica"]
            )

            results.append(result)

        self.results = results
        return results

    def _run_single_replica(
        self,
        replica_id: str,
        instance_id: str,
        instance_path: Path,
        epoch: int,
        slice_idx: int,
        replica_idx: int
    ) -> SPICATestResult:
        """
        Run a single test replica.

        For now, this is a placeholder that validates the instance exists.
        Real implementation would run tests defined in the instance.
        """
        # Check if instance is valid
        manifest_path = instance_path / "manifest.json"

        if not manifest_path.exists():
            return SPICATestResult(
                replica_id=replica_id,
                spica_id=instance_id,
                status="fail",
                error_message=f"Manifest not found: {manifest_path}"
            )

        try:
            manifest = json.loads(manifest_path.read_text())

            # Simple validation: instance has valid structure
            # Real tests would execute the instance's test suite

            return SPICATestResult(
                replica_id=replica_id,
                spica_id=instance_id,
                status="pass",
                exact_match_mean=0.95,  # Placeholder
                latency_p50_ms=150.0,
                latency_p95_ms=300.0,
                memory_peak_mb=512.0,
                cpu_percent=25.0,
                query_count=100
            )

        except Exception as e:
            logger.error(f"Test failed for {replica_id}: {e}")
            return SPICATestResult(
                replica_id=replica_id,
                spica_id=instance_id,
                status="fail",
                error_message=str(e)
            )

    def aggregate_replica_results(
        self,
        results: List[SPICATestResult]
    ) -> Dict[str, Any]:
        """
        Aggregate results across replicas by instance.

        Args:
            results: List of SPICATestResult objects

        Returns:
            Dict mapping instance_id to aggregated metrics
        """
        aggregated = {}

        # Group by SPICA instance
        by_instance = {}
        for result in results:
            if result.spica_id not in by_instance:
                by_instance[result.spica_id] = []
            by_instance[result.spica_id].append(result)

        # Aggregate metrics
        for instance_id, instance_results in by_instance.items():
            passed = sum(1 for r in instance_results if r.status == "pass")
            total = len(instance_results)

            # Average metrics across passing replicas
            passing = [r for r in instance_results if r.status == "pass"]
            if passing:
                avg_latency = sum(r.latency_p50_ms for r in passing) / len(passing)
                avg_exact_match = sum(r.exact_match_mean for r in passing) / len(passing)
            else:
                avg_latency = 0.0
                avg_exact_match = 0.0

            aggregated[instance_id] = {
                "pass_rate": passed / total if total > 0 else 0.0,
                "total_replicas": total,
                "passed": passed,
                "failed": total - passed,
                "avg_latency_p50_ms": avg_latency,
                "avg_exact_match_mean": avg_exact_match
            }

        return aggregated


# Export main classes
__all__ = ["SPICADomain", "SPICATestConfig", "SPICATestResult"]
