name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint & Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install ruff==0.13.1 pycln==2.5.0 bandit==1.8.6 semgrep==1.137.0
      - name: Ruff lint
        run: ruff check src tests
      - name: Ruff format check
        run: ruff format --check src tests
      - name: Pycln import hygiene
        run: pycln --all --check src tests
      - name: Bandit
        run: bandit -r src
      - name: Semgrep
        run: semgrep scan --config p/default --severity WARNING --error

  types:
    name: Type Check (mypy)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install mypy==1.18.2
      - name: Mypy
        run: mypy --config-file pyproject.toml src

  tests:
    name: Tests (pytest)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest
      - name: Pytest
        run: pytest -q

  accuracy:
    name: Accuracy Stack Smoke
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run tiny accuracy evaluation
        run: |
          python scripts/eval_accuracy.py \
            --config kloROS_accuracy_stack/config/accuracy_ci.yml \
            --qa kloROS_accuracy_stack/fixtures/mini/qa.jsonl \
            --out out \
            --limit 3
      - name: Show evaluation summary
        run: cat out/eval_report.md

  security:
    name: Dependency Audit
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-audit==2.9.0
          python -m pip install -r requirements.txt
      - name: pip-audit
        run: pip-audit --requirement requirements.txt
