name: CI

on:
  push:
    branches: [ main, feat/readme-device-helper ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install system deps required by native Python packages used by the project
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            python3-dev \
            libsndfile1 \
            libsndfile1-dev \
            libportaudio2 \
            portaudio19-dev \
            libasound2-dev \
            pkg-config \
            swig \
            libffi-dev \
            libssl-dev \
            libatlas-base-dev \
            libblas-dev \
            liblapack-dev \
            git \
            curl
          # Upgrade packaging tools and build wheels when possible
          python -m pip install --upgrade pip setuptools wheel
          # Install Python deps (use cached pip directory)
          python -m pip install --no-cache-dir -r requirements.txt || \
            (python -m pip install --upgrade pip setuptools wheel && python -m pip install -r requirements.txt)
            # No editable install here — repository is importable via PYTHONPATH in CI
            python -m pip install pytest
      - name: "Debug: Python environment"
        run: |
          python -V
          python -m pip --version
          python -m pip freeze | sed -n '1,200p'
      - name: Run smoke tests
        run: pytest -q tests/test_smoke.py
