name: CI

on:
  push:
    branches: [ main, feat/readme-device-helper ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install system deps required by native Python packages used by the project
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            python3-dev \
            libsndfile1 \
            libportaudio2 \
            portaudio19-dev \
            libasound2-dev \
            pkg-config
          # Now install Python deps
          pip install -r requirements.txt
          pip install pytest
      - name: Run smoke tests
        run: pytest -q tests/test_smoke.py
